# Generated by Django 3.1 on 2022-03-17 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_orderproduct'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderproduct',
            name='color',
        ),
        migrations.RemoveField(
            model_name='orderproduct',
            name='size',
        ),
    ]
